In [1]:
#Random Forest regressor
# 1. Import necessary library 
import pandas as pd

In [2]:
# 2. Load Dataset
Dataset = pd.read_csv("insurance_pre.csv")

In [3]:
Dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
# 3. Input Output split
Independent = Dataset.drop(columns=["charges"])
dependent = Dataset["charges"]

In [5]:
Independent

      age     sex     bmi  children smoker
0      19  female  27.900         0    yes
1      18    male  33.770         1     no
2      28    male  33.000         3     no
3      33    male  22.705         0     no
4      32    male  28.880         0     no
...   ...     ...     ...       ...    ...
1333   50    male  30.970         3     no
1334   18  female  31.920         0     no
1335   18  female  36.850         0     no
1336   21  female  25.800         0     no
1337   61  female  29.070         0    yes

[1338 rows x 5 columns]

In [6]:
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [7]:
#4 convert catagorical data
Independent = pd.get_dummies(Independent,drop_first=True)

In [8]:
Independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [9]:
# 5 Train test split
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test= train_test_split( Independent,dependent, test_size=0.03, random_state=0)

In [10]:
# 6 Scaling the feature
from sklearn.preprocessing import StandardScaler
sc = StandardScaler( )
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [11]:
# 5 Model_selection & cross_validation
import xgboost as xgb
from xgboost import XGBRegressor
XGB = XGBRegressor( n_estimators = 100, learning_rate = 1.1, random_state = 42 )
XGB.fit(X_train_scaled,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=1.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [12]:
#6 Viewing weight and bias value
#weight= DR.coef_
#print(f"Weight of the model { weight }")
#Bias = DR.intercept_
#print(f"Bias of the model { Bias }")

In [13]:
# 7 Model_Evalution & Digonestices
Y_predict = XGB.predict(X_test_scaled)

In [14]:
Y_predict

array([ 7060.966  ,  9092.104  , 48196.418  , 14000.751  ,  8512.084  ,
       26080.479  ,  1060.891  , 11379.902  ,  6894.927  ,  6399.7646 ,
        7220.621  , 20455.459  ,  7870.3086 ,  6015.528  , 20276.613  ,
       11045.685  , 10477.49   ,  2219.0745 ,  6692.1914 , 36088.066  ,
       28192.354  , 15972.227  , 11597.286  , 27834.701  , 10917.658  ,
        5443.766  ,  5883.3896 ,  9867.27   ,  1755.2979 ,  3572.1445 ,
       10141.791  , 46445.043  , 19196.996  , 11660.223  , 16281.271  ,
        2828.2527 , 11024.28   , 40933.418  , 39025.996  ,   393.61423,
       15371.326  ], dtype=float32)

In [15]:
# 8 Check r_score value performance of the Model
from sklearn.metrics import r2_score
r_score = r2_score(y_test,Y_predict)
r_score

0.8122692524118973

In [17]:
#9 Deployment model to file
import pickle
pickle.dump(XGB,open("XGB_regress_insur.svc","wb"))
model = pickle.load(open("XGB_regress_insur.svc","rb"))

In [18]:
#10 Predict the value
age = float(input("age"))
sex = int(input("sex"))
bmi = float(input("bmi"))
children = int(input("children")) 
smoke = int(input("smoke"))

age 25
sex 1
bmi 32
children 1
smoke 1

In [19]:
scaled_input = sc.transform([[age, sex, bmi, children, smoke]])
result = model.predict(scaled_input)
result

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([15737.242], dtype=float32)